### ISSUE TITLE
can we please allow merge without CR?

### ISSUE THREAD

**Issue by alexhsamuel** [sl-as-kj/tbl#5]
For obvious fixes, docs, etc.

**Comment by KyleSJohnston** [comment]
I've adjusted the permissions such that anyone in the organization in now an admin of the repo. Hopefully this allows us to merge, but there are no open PRs to use to verify this change. I'll close when I know I've reconfigured successfully.

**Comment by KyleSJohnston** [comment]
I've made an update that should allow merges without code review. I'll try to take a look at the PRs that are outstanding, but it's probably better that I'm no longer holding up a merge.
